/**
 * Pharmacy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryResponseDto { 
    id?: number;
    medicineId?: number;
    medicineName?: string;
    medicineManufacturer?: string;
    supplierId?: number;
    supplierName?: string;
    stockQuantity?: number;
    batchNumber?: string;
    expirationDate?: string;
}

