/**
 * Pharmacy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Medicine } from './medicine';
import { Supplier } from './supplier';


export interface Inventory { 
    id?: number;
    medicine?: Medicine;
    supplier?: Supplier;
    stockQuantity?: number;
    batchNumber?: string;
    expirationDate?: string;
    version?: number;
}

