/**
 * Pharmacy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { SaleResponseDto } from './sale-response-dto';
import { SortObject } from './sort-object';


export interface PageSaleResponseDto { 
    totalElements?: number;
    totalPages?: number;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<SaleResponseDto>;
    number?: number;
    sort?: SortObject;
    empty?: boolean;
}

