/**
 * Pharmacy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaleItemDto } from './sale-item-dto';


export interface SaleResponseDto { 
    id?: number;
    dateTime?: string;
    sellerName?: string;
    customerName?: string;
    totalAmount?: number;
    items?: Array<SaleItemDto>;
}

