/**
 * Pharmacy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Supplier { 
    id?: number;
    email?: string;
    name?: string;
    contactPerson?: string;
    phone?: string;
}

