spring.application.name=Pharmacy
spring.datasource.url=jdbc:mariadb://localhost:3306/cars_db

spring.datasource.username=haru
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

jwt.secret=vvPsH3KG7t5/QS7BfDnS3vSau8O7WykUy7kQjKPouQk=
jwt.expiration=86400000